services:
  - type: web
    name: spotify-streaming-dashboard
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      cp *.csv .
      cp *.joblib .
    startCommand: streamlit run streamlit_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free 