[theme]
base = "dark"
primaryColor = "#1DB954"  # Spotify green
backgroundColor = "#191414"  # Spotify black
secondaryBackgroundColor = "#282828"  # Spotify dark gray
textColor = "#FFFFFF"  # White
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false 